feat(structure): rename `deck` to `context`
Lullabot/gatsby-theme-adr pull request #51
Opened 2022-06-02 15:06 UTC by andy-blum

This PR updates the theme to use `context` in place of `deck` in ADR frontmatter, as "deck" is not the most intuitive name for this field.

2022-06-02 16:05 UTC, deviantintegral commented
Nice! Should we make it so `deck` still works? Otherwise, I think I would call this a compatibility break and warranting a 2.0 release.

2022-06-02 18:57 UTC, andy-blum commented
I've been working in `gatsby-node.js` in the `onCreateNode` hook, which I'm pretty sure is the right place to be doing this, but I've been unable to see - much less modify - node fields.

@e0ipso any chance you can take a look?

2022-06-04 05:11 UTC, e0ipso commented
Unfortunately this will be breaking BC for projects using this theme. The component props are part of the interface, via the component shadowing.

Let's make sure that the `example` site has some ADRs with `deck` and some with `context` to ensure BC.

2022-06-04 05:12 UTC, e0ipso requested changes
Unfortunately this will be breaking BC for projects using this theme. The component props are part of the interface, via the component shadowing.

Let's make sure that the example site has some ADRs with deck and some with context to ensure BC.

2022-07-21 21:57 UTC, deviantintegral commented
@andy-blum do you think you'll have time to pick this back up?

2022-11-01 18:20 UTC, andy-blum commented
@e0ipso I've addad an ADR with the `deck` key changed to `context`

2022-11-02 15:02 UTC, e0ipso commented on packages/gatsby-theme-adr/config/feedOptions.js
> +            description: edge.node.frontmatter.context,
Shouldn't we also grab `deck` in case a site upgrades but it's still using the old format?

2022-11-02 15:03 UTC, e0ipso requested changes

2022-11-02 15:03 UTC, e0ipso commented on packages/gatsby-theme-adr/config/feedOptions.js
> +                  context
Shouldn't we also grab `deck` in case a site upgrades but it's still using the old format? Also applies in other places.

2024-03-22 13:01 UTC, andy-blum commented
Closing this in favor of our site refactor.

2024-03-22 13:01 UTC, closed without merging